# Generated by Django 5.2.9 on 2025-12-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('regimen_fiscal', models.CharField(blank=True, choices=[('601', 'General de Ley Personas Morales'), ('603', 'Personas Morales con Fines No Lucrativos'), ('605', 'Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', 'Arrendamiento'), ('607', 'Régimen de Enajenación o Adquisición de Bienes'), ('608', 'Demás ingresos'), ('610', 'Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', 'Ingresos por Dividendos (socios y accionistas)'), ('612', 'Personas Físicas con Actividades Empresariales y Profesionales'), ('614', 'Ingresos por intereses'), ('615', 'Régimen de los ingresos por obtención de premios'), ('616', 'Sin obligaciones fiscales'), ('620', 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', 'Incorporación Fiscal'), ('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', 'Opcional para Grupos de Sociedades'), ('624', 'Coordinados'), ('625', 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', 'Régimen Simplificado de Confianza (RESICO) - Personas Físicas'), ('628', 'Régimen Simplificado de Confianza (RESICO) - Personas Morales'), ('629', 'Régimen de los ingresos por hidrocarburos'), ('630', 'Régimen de Enajenación de acciones en Bolsa de Valores')], help_text='Selecciona el régimen fiscal según el SAT', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('es_deudora', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Contables',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('fecha', models.DateTimeField()),
                ('emisor_rfc', models.CharField(max_length=13)),
                ('emisor_nombre', models.CharField(max_length=300)),
                ('receptor_rfc', models.CharField(max_length=13)),
                ('receptor_nombre', models.CharField(max_length=300)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado'), ('N', 'Nómina'), ('P', 'Pago')], max_length=1)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='xmls/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'unique_together': {('empresa', 'uuid')},
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descripcion', models.CharField(max_length=1000)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='core.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poliza', to='core.factura')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cuentacontable')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.poliza')),
            ],
        ),
    ]
