# Generated by Django 5.2.9 on 2025-12-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_contable',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTABILIZADA', 'Contabilizada'), ('EXCLUIDA', 'Excluida')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='naturaleza',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('C', 'Control/Neutro')], default='C', max_length=1),
        ),
    ]
