# Generated by Django 5.2.9 on 2025-12-15 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factura_estado_contable_factura_naturaleza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='impuestos_trasladados',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='creada_en',
        ),
        migrations.AlterField(
            model_name='concepto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='clave_prod_serv',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movimientopoliza',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='movimientopoliza',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movimientopoliza',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poliza'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='factura',
            name='archivo_xml',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_subida',
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador'), ('lectura', 'Lectura')], default='lectura', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Usuario',
                'verbose_name_plural': 'Usuarios por Empresa',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
