# Generated by Django 5.2.9 on 2025-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_factura_options_alter_factura_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='naturaleza',
            field=models.CharField(choices=[('D', 'Deudora'), ('A', 'Acreedora')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('CAPITAL', 'Capital'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto')], default='ACTIVO', max_length=10),
        ),
    ]
