# Generated by Django 5.2.9 on 2025-12-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuentacontable_naturaleza_cuentacontable_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_factura', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado'), ('N', 'Nómina'), ('P', 'Pago')], max_length=1)),
                ('es_default', models.BooleanField(default=False, help_text='Usar automáticamente para este tipo de factura')),
                ('cuenta_flujo', models.ForeignKey(help_text='Cliente/Banco (Ingreso) o Proveedor/Banco (Egreso)', on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_flujo', to='core.cuentacontable')),
                ('cuenta_impuesto', models.ForeignKey(blank=True, help_text='IVA Trasladado (Ingreso) o IVA Acreditable (Egreso)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_impuesto', to='core.cuentacontable')),
                ('cuenta_provision', models.ForeignKey(help_text='Ventas (Ingreso) o Gasto/Costo (Egreso)', on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_provision', to='core.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla Contable',
                'verbose_name_plural': 'Plantillas Contables',
            },
        ),
    ]
