# Generated by Django 5.2.9 on 2025-12-15 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plantillapoliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='plantilla_usada',
            field=models.ForeignKey(blank=True, help_text='Plantilla utilizada para generar esta póliza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_generadas', to='core.plantillapoliza'),
        ),
    ]
