# Generated by Django 5.2.9 on 2025-12-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_poliza_plantilla_usada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='agrupador_sat',
            field=models.CharField(blank=True, help_text='Código agrupador SAT Anexo 24 (ej: 101.01). DEBE heredarse a subcuentas.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Mayor'), (2, 'Subcuenta'), (3, 'Auxiliar')], default=1, help_text='Nivel jerárquico: 1=Mayor, 2=Subcuenta, 3=Auxiliar'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre (solo para subcuentas nivel 2 y auxiliares nivel 3)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='core.cuentacontable'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='rfc_tercero',
            field=models.CharField(blank=True, db_index=True, help_text='RFC del cliente/proveedor (para subcuentas específicas por tercero)', max_length=13, null=True),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['empresa', 'rfc_tercero'], name='core_cuenta_empresa_a315d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['empresa', 'padre'], name='core_cuenta_empresa_6234da_idx'),
        ),
    ]
