# Generated by Django 5.2.9 on 2025-12-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_uso_cfdi_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_sat',
            field=models.CharField(choices=[('Sin Validar', 'Sin Validar'), ('Vigente', 'Vigente'), ('Cancelado', 'Cancelado'), ('No Encontrado', 'No Encontrado'), ('Error', 'Error')], default='Sin Validar', help_text='Estado de la factura en el SAT', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='ultima_validacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última validación con el SAT', null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uuid',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
