# Generated by Django 5.2.9 on 2025-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backgroundtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Código SAT',
                'verbose_name_plural': 'Códigos SAT',
            },
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='codigo_sat',
            field=models.CharField(blank=True, db_index=True, help_text='Código agrupador SAT (Anexo 24)', max_length=20, null=True),
        ),
    ]
