# Generated by Django 5.2.9 on 2025-12-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_satcodigo_cuentacontable_codigo_sat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientopoliza',
            options={'verbose_name': 'Movimiento de Póliza', 'verbose_name_plural': 'Movimientos de Pólizas'},
        ),
        migrations.AddIndex(
            model_name='movimientopoliza',
            index=models.Index(fields=['cuenta', 'poliza'], name='core_movimi_cuenta__559258_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientopoliza',
            index=models.Index(fields=['poliza'], name='core_movimi_poliza__8f8bde_idx'),
        ),
    ]
