# Generated by Django 5.2.9 on 2025-12-17 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_movimientopoliza_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_factura', models.UUIDField(verbose_name='UUID del SAT')),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('emisor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('receptor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tenia_poliza', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Eliminación',
                'verbose_name_plural': 'Auditorías de Eliminación',
                'db_table': 'auditoria_eliminacion',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
