# Generated by Django 5.2.9 on 2025-12-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auditoriaeliminacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='editada_manualmente',
            field=models.BooleanField(default=False, help_text='Indica si la póliza fue editada manualmente'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última edición manual', null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='usuario_edicion',
            field=models.ForeignKey(blank=True, help_text='Usuario que editó la póliza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_editadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza', to='core.factura'),
        ),
    ]
